### ISSUE TITLE
Confuse order of providers

### ISSUE THREAD

**Issue by ChrisCoy** [antoniopataro/layered-nextjs#1]
file located at src/application/contexts/index.tsx.

when we write jsx code, we put a context inside another context, like <Context><AnotherCtx /></Content>, we intuitivelly know that AnotherCtx have acces to Context, and not the oposite, what means that bottom context have acces to the top one.

The way it was implemented is the inverse, in the array, the top context have access to the bottom one.

well, i dont think this is really bad thing, but i think its worthy mention it

**Comment by antoniopataro** [comment]
hey, @ChrisCoy! good point, man, you're right!

i think both ways aren't expressive in terms of hierarchy, but reading it from top to bottom, as you suggested, makes more sense than the current version, so I'm changing that! thank you!
